### ISSUE TITLE
Signin doesn't work

### ISSUE THREAD

**Issue by sebfar9172** [nmathey/finasync#17]
![image](https://github.com/nmathey/finasync/assets/52531214/e5364043-3b33-41cf-9282-aaf964d705fc)

**Comment by nmathey** [comment]
`INFO:root:Error [404]`

Got the same error on my side. Might be a change from Finary API authentification: I'll check with https://github.com/lasconic/finary_uapi which Finasync depend on.

**Comment by nmathey** [comment]
Might be related to this: https://github.com/lasconic/finary_uapi/pull/160 `'/auth/signin' will soon be retired`

**Comment by nmathey** [comment]
Confirmed :)

Please run `poetry update` command in order to update finary_uapi dependency package then run signing command again ;)

Let me know if ok

**Comment by sebfar9172** [comment]
Hello i have an another issue

![image](https://github.com/nmathey/finasync/assets/52531214/55d9de2b-3f75-425a-9ce9-dced31739e04)

**Comment by nmathey** [comment]
I can reproduce it and looks an issue from finary_uapi.

I raised an issue directly to the dedicated project: https://github.com/lasconic/finary_uapi/issues/177

**Comment by nmathey** [comment]
Are you using 2FA? 
Looks like the issue is linked as by deactivating it is working again.
It can be a workaround until we find the root cause.

**Comment by sebfar9172** [comment]
Yes i do
I will test without 2fa this evening

**Comment by sebfar9172** [comment]
I confirm that's work without 2FA

**Comment by lasconic** [comment]
With 2FA on, please try to run

```
python - m finasync signin 2FA_CODE
```

Where `2FA_CODE` is a valid code from Google Authentification.

**Comment by sebfar9172** [comment]
I have this error

![image](https://github.com/nmathey/finasync/assets/52531214/63fff098-44bb-42a6-a240-57823b4b46df)

**Comment by nmathey** [comment]
This is a different error from a small evolution I worked on :)
Did signin work ?

**Comment by sebfar9172** [comment]
I don't know i have the same error when i try to see the properties

![image](https://github.com/nmathey/finasync/assets/52531214/aa1dbb98-502c-4b04-bd3e-c16243e08e86)

**Comment by nmathey** [comment]
ok this is a different error that is on my side of code :)
I updated 24h ago you already get the latest code?
I'll have a second look at it today

**Comment by sebfar9172** [comment]
it's weird
i don't have the latest change

![image](https://github.com/nmathey/finasync/assets/52531214/24f69a5b-a97a-4b1f-936f-9932741211a3)

**Comment by sebfar9172** [comment]
that's works thanks
